Use t.Mapping not t.Dict for parameters
pallets/click pull request #2265
Opened 2022-04-29 15:20 UTC by altendky

https://docs.python.org/3/library/typing.html#typing.Dict
> To annotate arguments it is preferred to use an abstract collection type such as Mapping.

This PR does exactly that to fix the issue below.

- fixes #<issue number>

Checklist:

- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
  - :question: I have not added any tests since I'm not sure that click has hinting-specific tests.  I could add some code to exercise this though if you let me know where it would belong.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [ ] Run `pre-commit` hooks and fix any issues.
- [ ] Run `pytest` and `tox`, no tests failed.

2023-05-07 01:46 UTC, saroad2 requested changes
Hey @altendky , Thanks for the PR and sorry for the long delay!

This PR makes sense to me. I fixed some merging issues and we are ready to merge.
The only thing that I think worth fine tuning is the change note. I wrote a suggestion, but if you have better one - please feel free to paraphrase.

After this is fixed, we could merge!

2023-05-07 01:46 UTC, saroad2 commented on CHANGES.rst
> +-   Switch from ``typing.Dict`` to ``typing.MutableMapping`` for
```suggestion
-   Replace all ``typing.Dict`` occurrences to ``typing.MutableMapping`` for
```

2023-05-07 14:21 UTC, altendky commented
Your suggestion reads well to me.  Thanks for your interest and effort on this.

2023-05-07 15:49 UTC, saroad2 commented
I'm now rethinking that this PR might should be merged into *8.1.x* instead of *main*.

@davidism , I would appriciate your input on it.

2023-05-08 14:01 UTC, davidism commented
Yes, this can go in 8.1.x.

2023-05-08 15:03 UTC, merged