Added list of choices to termui prompt for user data if the data requested is a Choice
pallets/click pull request #496
Opened 2015-12-31 12:51 UTC by Rovanion

I found it odd that the user had to give incorrect input in order to be presented with the list of available options, for example:

```
Group by: something
Error: invalid choice: something. (choose from none, day, week, month)
```

In the above example the user is asked to give the program some interval to group by but offers no help as to what the valid inputs are until the user has incorrectly entered 'something'. With the modifications included in this commit the prompt would look as follows:

```
Group by (none, day, week, month):
```

It is now clear to the user that it has a limited set of options to chose from. This of course works in combination with default options.

```
Group by (none, day, week, month) [week]:
```

It is possible to disable the display of the choices by passing show_choices=False just like passing show_default=False works.

Also added a test for the new behaviour.

The last test of the test_chain.py test suite xFails, whatever that means, but it does that on master too so I don't think it's related to my changes.

2016-02-18 12:40 UTC, Rovanion commented
This PR now has conflicts that need to be resolved. But other than that, is there any feedback you want to leave, anything you want to change in order merge these changes?

2016-04-04 16:31 UTC, untitaker commented
Depending on how many choices there are, this might become too verbose. Wouldn't it be better if this is explained through a custom helptext?

2016-04-08 08:50 UTC, Rovanion commented
> Depending on how many choices there are, this might become too verbose.

We can imagine some click application having more than twenty available options in a single choice, then it could become messy - iff the feature was enabled. But then such a large number of options in a choice is probably the exception rather than the norm amongst click programs.  And since the display of the available options in a choice has to be explicitly enabled by the developer I don't see how this is an issue in the context of the click framework providing this feature for developers to use. We have to be able to trust the program developer not to explicitly enable features of click which are unfit for his situation.

> Wouldn't it be better if this is explained through a custom helptext?

This is automatic. It changes with the code and stays consistent with the program at all times. A custom help text has to be explicitly written by the developer as well as kept up to date by the same developer.

Part of what got me into using click was that it did much of the user facing documentation and interaction "for free" based on the program's internal structure. This is another step in that direction.

2016-04-08 17:53 UTC, untitaker commented on click/termui.py
> +def prompt(text, default=None, hide_input=False, confirmation_prompt=False,
We already have a `type` parameter, which could be used to pass `click.Choice` in.

Ideally we would then be able to refactor `prompt_for_value` to have no choices-specific code, and just pass the type in.

2016-04-08 17:53 UTC, untitaker commented
I've just come across this myself, you convinced me.

2016-04-11 10:09 UTC, Rovanion commented on click/termui.py
> +def prompt(text, default=None, hide_input=False, confirmation_prompt=False,
But we would still like to have the flag show_choices there right?

And what do you think it should default to& Right now it defaults to not show the available choices.

2016-04-11 16:35 UTC, untitaker commented on click/termui.py
> +def prompt(text, default=None, hide_input=False, confirmation_prompt=False,
Yes, I think it should be true by default.

Ideally it should also trunchate, but maybe for another time.

2016-04-22 16:45 UTC, untitaker commented
Hey @Rovanion any updates?

2016-04-22 17:13 UTC, Rovanion commented
@untitaker Haven't had any time to spend on the PR since last and since it took a couple of months for someone to get back to me in the first place I figured there was no rush.

I'll look into it when I get a free evening.

2016-10-30 16:14 UTC, Rovanion commented
@untitaker I've updated the code according to your suggestions and added documentation for show_choices to the docstring of `prompt`.

2016-10-30 16:18 UTC, untitaker requested changes
Great stuff, but there's a few leftovers.

2016-10-30 16:18 UTC, untitaker commented on tests/test_termui.py
> +    assert '(none, day, week, month)' in runner.invoke(cli, [], input='none').output
Could you assert the exact output here?

2016-10-30 16:18 UTC, untitaker commented on click/core.py
> +        else:
Can we leave this change out? It's not really necessary and a matter of taste, also I'm a proponent of minimal, topical PRs

2016-10-30 16:18 UTC, untitaker commented on click/termui.py
> +def _build_prompt(text, suffix, show_default=False, default=None, show_choices=False, type=None):
Why default value of `False` here?

2016-10-30 16:18 UTC, untitaker commented on click/core.py
> +                 type=None, help=None, hidden=False, show_choices=True, **attrs):
What will happen with this param? Right now it gets discarded.

2016-10-30 16:44 UTC, Rovanion commented on tests/test_termui.py
> +    assert '(none, day, week, month)' in runner.invoke(cli, [], input='none').output
Why would that be clearer? The entire output is 'G (none, day, week, month): none\n' where the only part of this feature present in the output is '(none, day, week, month)'.

On the other hand, I only repeated the style I found in the progress bar test.

```python
    assert label in runner.invoke(cli, []).output
```

2016-10-30 17:03 UTC, Rovanion commented on click/core.py
> +        else:
Done deal.

2016-10-30 17:33 UTC, Rovanion commented on click/core.py
> +                 type=None, help=None, hidden=False, show_choices=True, **attrs):
That doesn't even belong there. It should be in the Option class so that it can be toggled on an per option basis.

2016-10-31 20:46 UTC, untitaker commented on click/core.py
> +                 type=None, help=None, hidden=False, show_choices=True, **attrs):
Yeah but right now it appears to get ignored.

2016-10-31 21:09 UTC, Rovanion commented
Sorry if I wasn't clear enough in my earlier message: I have a fix in the
works. Just gotta test it a bit, commit and push.

2016-10-31 21:46 GMT+01:00 Markus Unterwaditzer <notifications@github.com>:

> *@untitaker* commented on this pull request.
> ------------------------------
>
> In click/core.py <https://github.com/pallets/click/pull/496>:
>
> > @@ -1461,7 +1461,7 @@ def __init__(self, param_decls=None, show_default=False,
>                   prompt=False, confirmation_prompt=False,
>                   hide_input=False, is_flag=None, flag_value=None,
>                   multiple=False, count=False, allow_from_autoenv=True,
> -                 type=None, help=None, hidden=False, **attrs):
> +                 type=None, help=None, hidden=False, show_choices=True, **attrs):
>
> Yeah but right now it appears to get ignored.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pallets/click/pull/496>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAmnx74h5mimNNuDd3J3jgbKCv1ZcY4uks5q5lOYgaJpZM4G9M0k>
> .
>

2016-10-31 22:18 UTC, Rovanion commented
With this latest version of the commit, hash 1f1e1a5, I've added an additional test to make sure that you can both turn the choices list on and off in the prompt. I could still rewrite the tests to assert against the exact string but then the tests would test for other features of click than that in this PR, they would stop passing even if code was changed which is unrelated to the choices list.

2016-11-01 21:44 UTC, untitaker approved these changes

2016-11-01 21:45 UTC, untitaker requested changes
Cool stuff, please also add a changelog entry

2016-11-02 09:41 UTC, Rovanion commented
And now there's a changelog entry!

2016-11-04 18:08 UTC, untitaker approved these changes

2016-11-04 18:15 UTC, merged