remove hard dependency on 'locale' binary for PY3
pallets/click pull request #880
Opened 2017-10-23 11:07 UTC by mbargull

Generating Click's error message/`RuntimeError` for Python 3 under a non-unicode locale requires the `locale` command to be available. `locale` might not be available, though, for instance in minimal images used for CI services, e.g., https://github.com/bitnami/minideb.

With this minimal change the "extra" information for the error will be
```python
extra = (
    '\n\n'
    'Additional information: on this system no suitable UTF-8\n'
    'locales were discovered.  This most likely requires resolving\n'
    'by reconfiguring the locale system.'
)
```
if `locale` is not available, which is still seems reasonable in my eyes.

2018-03-27 22:16 UTC, blueyed requested changes

2018-03-27 22:16 UTC, blueyed commented on click/_unicodefun.py
> +        except FileNotFoundError:
I guess this code is not covered in tests: `FileNotFoundError` is not available on py27.

2018-03-27 22:18 UTC, blueyed approved these changes
Sorry, this is py3 code - missed that.

2018-03-31 18:13 UTC, closed without merging

2018-04-02 18:58 UTC, mbargull commented
For posterity (or as a reminder for my future self):
The closing https://github.com/pallets/click/commit/7eb990fab5783b32c7028b0aa8a752e6862d0997 uses `OSError` instead of `FileNotFoundError` and thus it also catches cases where `locale` may exists but could not be run, e.g., due to a `PermissionError`.

2019-03-06 16:22 UTC, blueyed commented
@aktivkohle 
No idea really myself.

But the problem is actually here already then: https://github.com/pallets/click/blob/c6042bf2607c5be22b1efef2e42a94ffd281434c/click/_unicodefun.py#L54-L60
Everything below (including the "locale" call) is meant to provide extra information for the error.

Why/how does this fail for you?
```python
        import locale
        fs_enc = codecs.lookup(locale.getpreferredencoding()).name
```

As for patching, you could probably monkeypatch `_verify_python3_env` to do nothing.

It might be nice to provide a click option to skip this check, and maybe then also look for some environment variable to do this (e.g. `CLICK_SKIP_VERIFY_ENV`).



> why on earth does click need locale so badly?

Good question.  From a quick grep it might for e.g. https://github.com/pallets/click/blob/c6042bf2607c5be22b1efef2e42a94ffd281434c/click/types.py#L107-L112 and other places where bytes are decoded, and click wants to ensure that this is proper?!

It was added in 2014 (9ab74c3), maybe mainly to help with transitioning to py3?!

2019-03-06 16:55 UTC, mitsuhiko commented
> I don't get it, argparse is happy, why is click so demanding?

Because you get a python unicode config restricted to ASCII in such environments which is why this was added. It fundamentally points out that there is something wrong with the unicode setup on your machine.

Click assumes this is a resolvable error. If there are situations where you cannot resolve this, that would be interesting.

2019-03-07 10:16 UTC, aktivkohle commented
@blueyed thanks for looking into it and the detailed answer. You asked how _that_ fails for me. Well, it doesn't fail, `fs_enc` just ends up holding the string `'ascii'`, and so execution keeps going past line 60 and the return statement doesn't run. Once the section I posted has run, you end up with `good_locales` being `set()` and `has_c_utf8` being `False`. So it ends up raising its `RuntimeError` _"because Python 3 was configured to use ASCII as encoding for the environment... on this system no suitable UTF-8 locales were discovered.  This most likely requires resolving by reconfiguring the locale system... Click discovered that you exported a UTF-8 locale but the locale system could not pick up from it because it does not exist.  The exported locale is "en_GB.UTF-8" but it is not supported"_.

I am going to hack the library like this and see if it helps:
```
def _verify_python3_env():
    """Ensures that the environment is good for unicode on Python 3."""
    # ...Not!
    return
```

@mitsuhiko thanks for the reply, yes there is something wrong with the unicode setup on the device. It is not that it is _not_ resolvable but that I have spent too many hours trying to resolve it without knowing why click even needs it. Python is my area not such details for custom linux builds. Getting locale and unicode functioning properly will happen in a future sprint, but for now, I either get click to work or the CLI will be built with bash scripts rather than with click and python.

2019-03-07 10:36 UTC, blueyed commented
@aktivkohle 
To be clear, you are not seeing any error with `python -c 'import codecs, locale; c = codecs.lookup(locale.getpreferredencoding()); print(c, c.name)'`?

2019-03-07 10:42 UTC, mitsuhiko commented
To give a bit of explanation of why this check exists in click it's important to understand how it used to operate and how it operates now. When click was written it implemented unicode handling itself and it assumed utf-8 for such situations. That's still what it does on python2.

On Python 3 we need to use the Python 3 unicode handling for this. Reason for this is that with the exception of exporting `PYTHONIOENCODING` as environment variable there is no good way to force the unicode handling in Python to override the platform detection.

Since the world consists of also non english speakers I wanted to ensure that people know early that they have a problem and not the first time a non ascii character is being printed. Silencing this error is just going to postpone the issue until you are going to work with the first non ascii character.

Alternatively you can just `export PYTHONIOENCODING=utf-8` before running your script and this is likely to resolve this issue as well.

2019-03-07 12:26 UTC, aktivkohle commented
@blueyed there is no error with your command it simply returns:
`<codecs.CodecInfo object for encoding ascii at 0x7f87582348> ascii`

Well the good news is my little hack has worked, can keep moving with it for now!

@mitsuhiko `PYTHONIOENCODING=utf-8` is already in the environment it was recently put there to make our python handle unicode at all. Is unfortunately not enough to resolve it. Here is one of the symptoms of how unicode on my branch here is not fully healthy:
```
~# export LC_ALL=en_US.UTF-8
~# export LANG=en_US.UTF-8
~# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
It's well off topic to debate how to fix this in the linux, but if someone does know what the magic bullet is say or send me an email.

Instead of it being a hard dependency with `raise RuntimeError` it should probably be a collection of warnings that your system won't display non-English characters. I was thinking of submitting a pull request  then saw some stuff I'd never seen before `stacklevel=bad_frame` and the function `_find_unicode_literals_frame():` The warnings were not just coming from a few print statements..